include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true
    avoid_renaming_method_parameters: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - '**/*.freezed.dart'  
    - '**/*.g.dart'  
    
 