name: mondaymorning
description: Monday Morning flutter app
publish_to: "none"
version: 2.0.7+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer:
  auto_route:
  flutter:
    sdk: flutter
  flutter_riverpod:
  url_launcher:
  auto_size_text:
  material_design_icons_flutter:
  webview_flutter:
  google_fonts:
  graphql_flutter:
  json_serializable:

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  very_good_analysis:
  

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
