name: mondaymorning
description: Monday Morning flutter app
publish_to: "none"
version: 2.0.7+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.7.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.9
  graphql_flutter: ^5.0.0
  json_serializable: ^4.1.4

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
