name: mondaymorning
description: Monday Morning flutter app
publish_to: "none"
version: 2.0.7+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  # State Management
  stacked: ^1.7.6

  # Dependency Injection
  injectable: ^1.0.5
  get_it: ^5.0.3

  # Navigation
  auto_route: ^0.6.9

  # Services
  stacked_services: ^0.6.0+1

  # Theme Management
  stacked_themes: ^0.2.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9

  # Local Database - code generation
  hive_generator: ^0.8.2

  # Dependency Injection - code generation
  injectable_generator: ^1.0.6

  # Mocking
  mockito: ^4.1.3

  # Lint
  lint: ^1.0.0

  # Navigation - code generation
  auto_route_generator: ^0.6.9

flutter:
  uses-material-design: true
