name: mondaymorning
description: Monday Morning flutter app
publish_to: "none"
version: 2.0.7+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  flutter_riverpod: ^0.14.0+3
  freezed: ^0.14.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
