name: mondaymorning
description: Monday Morning flutter app
publish_to: 'none'
version: 2.0.7+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Local Database
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  #Mocking 
  mockito: ^4.1.3

  # State Management
  stacked: 1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner: ^1.10.9

  # Local Database - code generation
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
