name: mondaymorning
description: Monday Morning flutter app
publish_to: "none"
version: 2.0.7+19

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  auto_route: ^5.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  flutter_markdown: ^0.6.12
  url_launcher: ^6.1.5
  auto_size_text: ^3.0.0
  material_design_icons_flutter: ^5.0.6996
  webview_flutter: ^3.0.4
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  json_serializable: ^6.2.0
  carousel_slider: ^4.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  very_good_analysis: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
