name: mondaymorning
description: The cross-platform Mobile Application for Monday Morning under Project Infinity

publish_to: 'none'

version: 3.0.8+37

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.2
  carousel_slider: ^4.1.1
  firebase_analytics: ^10.0.3
  firebase_app_installations: ^0.2.1+2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_markdown: ^0.6.13
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  hooks_riverpod: ^2.0.2
  json_annotation: ^4.7.0
  material_design_icons_flutter: ^6.0.7096
  moment_dart: ^0.10.4
  riverpod_annotation: ^1.0.4
  toggle_switch: ^2.0.1
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.7
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  flutter_svg: ^1.1.6

dev_dependencies:
  analyzer: ^5.2.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    # - assets/i18n/
    - assets/images/light/
    - assets/images/dark/
    - assets/images/common_images/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/light/mm_logo_blue.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/images/light/mm_logo_blue.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/light/mm_logo_blue.png'
    background_color: '#FFFFFF'
    theme_color: '#006DCC'
