name: mondaymorning
description: The cross-platform Mobile Application for Monday Morning under Project Infinity

publish_to: 'none'

version: 3.0.0+27

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  auto_route: ^5.0.2
  carousel_slider: ^4.1.1
  firebase_analytics: ^10.0.3
  firebase_app_installations: ^0.2.1+2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_markdown: ^0.6.13
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  hooks_riverpod: ^2.0.2
  json_annotation: ^4.7.0
  moment_dart: ^0.10.4
  riverpod_annotation: ^1.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  analyzer: ^5.2.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    # - assets/i18n/
    - assets/images/light/
    - assets/images/dark/
    - assets/fonts/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_sans_pro/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_pro/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_pro/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/source_sans_pro/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/light/mm_logo_blue.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/images/light/mm_logo_blue.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/light/mm_logo_blue.png'
    background_color: '#FFFFFF'
    theme_color: '#006DCC'
