name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.18.2"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/flutter-apk/app-release.apk
